version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 4f0efV/bdZ9RuKTKFbnBKgNvVcLCxEKxNYC/2Y6ta0qHYuuaZNzpGOSeW52rdAQ+
before_build:
  - dotnet restore
  - nuget restore "Castle.Sharp2Js.Tests.sln"
build:
  project: Castle.Sharp2Js.Tests.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""Castle.Sharp2Js.Tests\bin\$env:CONFIGURATION\Castle.Sharp2Js.Tests.dll"" /noshadow" -filter:"+[Castle.Sharp2Js]*" -excludebyattribute:*.ExcludeFromCodeCoverageAttribute -output:opencoverCoverage.xml

    & new-variable -name coveralls -visibility public -value (Resolve-Path ".\packages\coveralls.net.*\tools\csmacnz.Coveralls.exe").ToString()

    $env:APPVEYOR_BUILD_NUMBER

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
